FRAGMENT = [
    {"q": "Which of the following is an example of a physical environment?",
     "opts": ["Botanic Garden", "Colorado River", "Marina Bay Sands", "Oil palm plantations"],
     "ans": 1,
     "explain": "The Colorado River is a naturally formed feature; the others are man-made or cultivated.",
     "topic_id": 301},
    {"q": "Which of the following is not a human activity that causes changes to the physical environment?",
     "opts": ["Deforestation", "Mining", "Pollution", "Tsunami"],
     "ans": 3,
     "explain": "A tsunami is a natural process, not a human activity.",
     "topic_id": 301},
    {"q": "Which of the following statement about the Earth is correct?",
     "opts": ["Earth has a shorter orbit than Mercury.",
              "Earth is much bigger than Jupiter.",
              "Earth is the only planet that is able to support life.",
              "Earth is the planet that is nearest to the Sun."],
     "ans": 2,
     "explain": "Earth is the only planet known to support life.",
     "topic_id": 301},
    {"q": "Why does the Sun appear to rise in the east and set in the west?",
     "opts": ["It is because the Earth rotates westward.",
              "It is because the Earth rotates eastward.",
              "It is because the Sun rotates westward.",
              "It is because the Sun rotates eastward."],
     "ans": 1,
     "explain": "The Earth rotates eastward, making the Sun appear to move from east to west.",
     "topic_id": 301},
    {"q": "Contour lines which are close together represent ____.",
     "opts": ["a gentle slope on a map", "a hill on a map",
              "a lowland area on a map", "a steep slope on a map"],
     "ans": 3,
     "explain": "Closely spaced contour lines indicate a steep gradient.",
     "topic_id": 302},
    {"q": "What is normally used to locate a place in an atlas?",
     "opts": ["grid references", "letter-number system",
              "latitudes and longitudes", "lengths and widths"],
     "ans": 2,
     "explain": "Latitude and longitude are used to locate places in an atlas.",
     "topic_id": 301},
    {"q": "Which of the following correctly shows 1 cm on the map represents 1 km on actual ground?",
     "opts": ["1:100", "1:1000", "1:10000", "1:100000"],
     "ans": 3,
     "explain": "1 km = 100000 cm, so 1 cm to 1 km is a scale of 1:100000.",
     "topic_id": 301},
    {"q": "Which is the most accurate way to locate Singapore on the map?",
     "opts": ["Singapore is located at 1 deg N, 103 deg E.",
              "Singapore is located at the centre of South-East Asia.",
              "Singapore is located in the Northern Hemisphere.",
              "Singapore is located to the South of Peninsular Malaysia."],
     "ans": 0,
     "explain": "Latitude and longitude coordinates give the most precise location.",
     "topic_id": 301},
    {"q": "The structure of the Earth has three layers labelled 1, 2 and 3 from the outside inwards. Which option correctly names parts 1, 2 and 3?",
     "opts": ["Crust / Mantle / Core", "Core / Crust / Mantle",
              "Mantle / Core / Crust", "Mantle / Crust / Core"],
     "ans": 0,
     "explain": "From the outside inwards the Earth's layers are crust, mantle then core.",
     "topic_id": 302},
    {"q": "A rock shows clearly visible horizontal layers (strata). What is this rock type?",
     "opts": ["Igneous", "Metamorphic", "Molten", "Sedimentary"],
     "ans": 3,
     "explain": "Visible layering (strata) is characteristic of sedimentary rock.",
     "topic_id": 302},
    {"q": "Which of the following indicates that movement of the Earth's plates is still going on?",
     "opts": ["Landslides", "Occurrence of earthquakes",
              "Occurrence of storms", "Weathering of mountains"],
     "ans": 1,
     "explain": "Earthquakes are caused by ongoing movement of the Earth's plates.",
     "topic_id": 302},
    {"q": "Water seeps into cracks in a rock, freezes, expands and widens the cracks, breaking the rock apart. Which of the following is a likely location for this weathering process?",
     "opts": ["Antarctica", "Amazon rainforest", "Pacific Ocean", "Sahara Desert"],
     "ans": 0,
     "explain": "Freeze-thaw (frost) weathering needs temperatures fluctuating around freezing point, as in Antarctica.",
     "topic_id": 302},
    {"q": "A mushroom-shaped rock is found in the desert with only its base eroded. Which best explains why only the base of the rock was eroded?",
     "opts": ["The water level was only high enough to reach the base of the rock",
              "The sand is heavy and cannot be blown to a high level in the air",
              "The strength of the wave is too weak to erode other parts of the rock",
              "The erosion process is too short for the entire rock to be fully eroded"],
     "ans": 1,
     "explain": "Wind carries heavy sand close to the ground, so abrasion erodes mainly the base.",
     "topic_id": 302},
]
