FRAGMENT = [
    {"q": "The study of Geography is about the interaction between ____.",
     "opts": ["human and physical environments",
              "man-made and human environments",
              "natural and physical environments",
              "human and animal environments"],
     "ans": 0,
     "explain": "Geography studies the interaction between human and physical environments.",
     "topic_id": 301},
    {"q": "Which of the following is not a component of the human environment?",
     "opts": ["Rubber plantation", "Power lines", "River", "Canal"],
     "ans": 2,
     "explain": "A river is a natural (physical) feature, not part of the human environment.",
     "topic_id": 301},
    {"q": "Which one of the following activities will least damage the environment?",
     "opts": ["Using water from the river to water the crops",
              "Dumping untreated sewage into the sea",
              "Building a beach resort",
              "Throwing litter into the drains"],
     "ans": 0,
     "explain": "Using river water to water crops causes the least environmental damage.",
     "topic_id": 301},
    {"q": "Which of the following descriptions about the !Kung Bushmen is NOT true?",
     "opts": ["They use simple tools to hunt for a living.",
              "They make big changes to their environment in order to survive.",
              "They use ostrich eggs to collect water.",
              "They do not build permanent shelters as they are always on the lookout for food and water."],
     "ans": 1,
     "explain": "The !Kung Bushmen make minimal changes to their environment; they adapt to it instead.",
     "topic_id": 309},
    {"q": "The horizontal lines on a grid map are called ____.",
     "opts": ["axis", "equator", "northings", "eastings"],
     "ans": 2,
     "explain": "Horizontal grid lines on a map are called northings.",
     "topic_id": 301},
    {"q": "A ____ refers to an imaginary line joining points or places of the same height.",
     "opts": ["latitude", "scale", "longitude", "contour"],
     "ans": 3,
     "explain": "A contour joins points of equal height on a map.",
     "topic_id": 302},
    {"q": "The 0 degree latitude is also known as the ____.",
     "opts": ["Tropic of Capricorn", "Tropic of Cancer", "Equator", "North Pole"],
     "ans": 2,
     "explain": "The 0 degree line of latitude is the Equator.",
     "topic_id": 301},
    {"q": "The action of running water commonly takes place in ____.",
     "opts": ["sandy beaches in Australia", "deserts in Africa",
              "rivers in Thailand", "polar regions in Alaska"],
     "ans": 2,
     "explain": "Running water acts most commonly in rivers.",
     "topic_id": 307},
    {"q": "Maps i) are tools used in planning; ii) are sources of information; iii) are used to calculate the distances between places accurately; iv) are used to record changes over time. Which is correct?",
     "opts": ["i and iii only", "ii and iv only",
              "i, ii and iv only", "all of the above"],
     "ans": 2,
     "explain": "Maps cannot give perfectly accurate distances, so iii is excluded; i, ii and iv are correct.",
     "topic_id": 301},
    {"q": "Molten rock which is found in the mantle layer is known as ____.",
     "opts": ["lava", "magma", "rock fragments", "vulcanicity"],
     "ans": 1,
     "explain": "Molten rock in the mantle is magma; it is called lava only after it reaches the surface.",
     "topic_id": 302},
]
