FRAGMENT = [
    {"q": "Which of the following are components of the physical environment?",
     "opts": ["Air, land, water, waste", "Air, soil, buildings, climate",
              "Air, land, water, living environment",
              "Solar system, temperature, wind, rain"],
     "ans": 2,
     "explain": "The physical environment is made up of air, land, water and the living environment.",
     "topic_id": 301},
    {"q": "Which of the following is an example of a human feature?",
     "opts": ["Ponds", "Rivers", "Reservoirs", "Sea"],
     "ans": 2,
     "explain": "Reservoirs are man-made, so they are a human feature.",
     "topic_id": 301},
    {"q": "Which of the following explains why the Earth is fragile?",
     "opts": ["Human activities like driving a car release toxic gases which are harmful to life on Earth",
              "Many plants and trees are becoming extinct due to deforestation",
              "The Earth is getting hotter because it is moving nearer to the Sun",
              "All of the above"],
     "ans": 0,
     "explain": "Human activities such as driving release toxic gases harmful to life on Earth.",
     "topic_id": 310},
    {"q": "Which of the following pairs of items are useful natural resources?",
     "opts": ["Motor vehicles and power stations", "Electricity and fire",
              "Fire and electronic gadgets", "Water and wood"],
     "ans": 3,
     "explain": "Water and wood occur naturally and are natural resources.",
     "topic_id": 308},
    {"q": "Technology is ____.",
     "opts": ["old machinery", "learning new skills",
              "teaching new skills to people", "understanding the environment"],
     "ans": 2,
     "explain": "Technology is the application of knowledge and skills to solve problems.",
     "topic_id": 301},
    {"q": "The five main oceans on Earth are Atlantic, Pacific, ____.",
     "opts": ["Indian, Arctic and Southern", "African, Arctic and Southern",
              "Indian, African and Southern", "Indian, Arctic and Antarctica"],
     "ans": 0,
     "explain": "The five oceans are Pacific, Atlantic, Indian, Arctic and Southern.",
     "topic_id": 301},
    {"q": "Maps have many uses. Which of the following is not one of them?",
     "opts": ["Sources of information", "Proof of human existence",
              "Record of changes", "Tools used in planning"],
     "ans": 1,
     "explain": "Maps are not used as proof of human existence.",
     "topic_id": 301},
    {"q": "All topographical maps have vertical grid lines called ____ and horizontal grid lines called ____.",
     "opts": ["Eastings, Northings", "Northings, Eastings",
              "Latitudes, Longitudes", "Longitudes, Latitudes"],
     "ans": 0,
     "explain": "Vertical grid lines are Eastings; horizontal grid lines are Northings.",
     "topic_id": 301},
    {"q": "Different ____ on maps are used to show sizes and levels of details.",
     "opts": ["scales", "rulers", "grid references", "arrows"],
     "ans": 0,
     "explain": "Different map scales show different sizes and levels of detail.",
     "topic_id": 301},
    {"q": "When plates meet, ____ mountains are often formed.",
     "opts": ["rift", "block", "fold", "horst"],
     "ans": 2,
     "explain": "Colliding plates compress crust upward to form fold mountains.",
     "topic_id": 302},
    {"q": "The belt around the Pacific Ocean where a large number of the world's volcanoes are found is called ____.",
     "opts": ["Pacific Ring of Five", "Pacific Ring of Fire",
              "Pacific Ocean of Five", "Pacific Ocean of Fire"],
     "ans": 1,
     "explain": "It is called the Pacific Ring of Fire.",
     "topic_id": 302},
    {"q": "The Earth's crust is made up of several ____ which can slide past, pull apart from or push towards each other.",
     "opts": ["oceans", "internal forces", "magma chambers", "plates"],
     "ans": 3,
     "explain": "The crust is made up of several tectonic plates.",
     "topic_id": 302},
    {"q": "Which of the following is not an element of climate?",
     "opts": ["Wind", "Air pressure", "Temperature", "Dust particles"],
     "ans": 3,
     "explain": "Dust particles are not an element of climate.",
     "topic_id": 303},
    {"q": "The temperate climate experiences ____.",
     "opts": ["four seasons in a year", "high rainfall all year round",
              "high temperature all year round",
              "extreme and harsh conditions all year round"],
     "ans": 0,
     "explain": "The temperate climate has four distinct seasons in a year.",
     "topic_id": 304},
]
