QUESTIONS = [
    {'q': 'Which of the following is an example of a physical environment?', 'opts': ['Botanic Garden', 'Colorado River', 'Marina Bay Sands', 'Oil palm plantation'], 'ans': 1, 'explain': 'A physical environment is natural and not made or managed by people; the Colorado River is a natural feature.'},
    {'q': 'Which of the following is NOT a human activity that causes changes to the physical environment?', 'opts': ['Deforestation', 'Mining', 'Pollution', 'Tsunami'], 'ans': 3, 'explain': 'A tsunami is a natural event, not a human activity.'},
    {'q': 'Which of the following statements about the Earth is correct?', 'opts': ['Earth has a shorter orbit than Mercury.', 'Earth is much bigger than Jupiter.', 'Earth is the only planet that is able to support life.', 'Earth is the planet that is nearest to the Sun.'], 'ans': 2, 'explain': 'Earth is the only known planet able to support life; it is not the closest to the Sun nor larger than Jupiter.'},
    {'q': 'Why does the Sun appear to rise in the east and set in the west?', 'opts': ['Because the Earth rotates westward.', 'Because the Earth rotates eastward.', 'Because the Sun rotates westward.', 'Because the Sun rotates eastward.'], 'ans': 1, 'explain': 'The Earth rotates eastward (west to east), so the Sun appears to move from east to west across the sky.'},
    {'q': 'Contour lines which are close together represent ____.', 'opts': ['a gentle slope on a map', 'a hill on a map', 'a lowland area on a map', 'a steep slope on a map'], 'ans': 3, 'explain': 'Closely spaced contour lines indicate a steep slope; widely spaced lines indicate a gentle slope.'},
    {'q': "Which of the following indicates that movement of the Earth's plates is still going on?", 'opts': ['Landslides', 'Occurrence of earthquakes', 'Occurrence of storms', 'Weathering of mountains'], 'ans': 1, 'explain': 'Earthquakes are caused by ongoing movement of tectonic plates.'},
    {'q': 'The structure of the Earth has three layers labelled 1, 2 and 3 from the outside inwards. Which option correctly names parts 1, 2 and 3?', 'opts': ['Crust / Mantle / Core', 'Core / Crust / Mantle', 'Mantle / Core / Crust', 'Mantle / Crust / Core'], 'ans': 0, 'explain': "From the outside inwards the Earth's layers are crust, mantle then core."},
    {'q': 'A rock shows clearly visible horizontal layers (strata). What is this rock type?', 'opts': ['Igneous', 'Metamorphic', 'Molten', 'Sedimentary'], 'ans': 3, 'explain': 'Visible layering (strata) is characteristic of sedimentary rock.'},
    {'q': 'Water seeps into cracks in a rock, freezes, expands and widens the cracks, breaking the rock apart. Which of the following is a likely location for this weathering process?', 'opts': ['Antarctica', 'Amazon rainforest', 'Pacific Ocean', 'Sahara Desert'], 'ans': 0, 'explain': 'Freeze-thaw (frost) weathering needs temperatures fluctuating around freezing point, as in Antarctica.'},
    {'q': 'A mushroom-shaped rock is found in the desert with only its base eroded. Which best explains why only the base of the rock was eroded?', 'opts': ['The water level was only high enough to reach the base of the rock', 'The sand is heavy and cannot be blown to a high level in the air', 'The strength of the wave is too weak to erode other parts of the rock', 'The erosion process is too short for the entire rock to be fully eroded'], 'ans': 1, 'explain': 'Wind carries heavy sand close to the ground, so abrasion erodes mainly the base.'},
    {'q': 'A ____ refers to an imaginary line joining points or places of the same height.', 'opts': ['latitude', 'scale', 'longitude', 'contour'], 'ans': 3, 'explain': 'A contour joins points of equal height on a map.'},
    {'q': 'Molten rock which is found in the mantle layer is known as ____.', 'opts': ['lava', 'magma', 'rock fragments', 'vulcanicity'], 'ans': 1, 'explain': 'Molten rock in the mantle is magma; it is called lava only after it reaches the surface.'},
    {'q': 'When plates meet, ____ mountains are often formed.', 'opts': ['rift', 'block', 'fold', 'horst'], 'ans': 2, 'explain': 'Colliding plates compress crust upward to form fold mountains.'},
    {'q': "The belt around the Pacific Ocean where a large number of the world's volcanoes are found is called ____.", 'opts': ['Pacific Ring of Five', 'Pacific Ring of Fire', 'Pacific Ocean of Five', 'Pacific Ocean of Fire'], 'ans': 1, 'explain': 'It is called the Pacific Ring of Fire.'},
    {'q': "The Earth's crust is made up of several ____ which can slide past, pull apart from or push towards each other.", 'opts': ['oceans', 'internal forces', 'magma chambers', 'plates'], 'ans': 3, 'explain': 'The crust is made up of several tectonic plates.'},
]

SUBTOPIC_RANGES = [('Contours & Relief', 0, 4), ('Cross-Sections', 4, 8), ('Interpreting Photographs', 8, 12), ('Geographical Information Systems (GIS)', 12, 15)]
