QUESTIONS = [
    {'q': 'What is normally used to locate a place in an atlas?', 'opts': ['grid references', 'letter-number system', 'latitudes and longitudes', 'lengths and widths'], 'ans': 2, 'explain': 'Atlases use latitude and longitude to give the exact location of a place.'},
    {'q': 'Which of the following correctly shows 1 cm on the map represents 1 km on actual ground?', 'opts': ['1:100', '1:1000', '1:10000', '1:100000'], 'ans': 3, 'explain': '1 km = 100 000 cm, so 1 cm to 1 km is a scale of 1:100000.'},
    {'q': 'Which is the most accurate way to locate Singapore on a map?', 'opts': ['Singapore is located at 1 deg N, 103 deg E.', 'Singapore is located at the centre of South-East Asia.', 'Singapore is located in the Northern Hemisphere.', 'Singapore is located to the south of Peninsular Malaysia.'], 'ans': 0, 'explain': 'Giving the latitude and longitude (1 deg N, 103 deg E) is the most precise way to locate a place.'},
    {'q': 'Which of the following statement about the Earth is correct?', 'opts': ['Earth has a shorter orbit than Mercury.', 'Earth is much bigger than Jupiter.', 'Earth is the only planet that is able to support life.', 'Earth is the planet that is nearest to the Sun.'], 'ans': 2, 'explain': 'Earth is the only planet known to support life.'},
    {'q': 'Which is the most accurate way to locate Singapore on the map?', 'opts': ['Singapore is located at 1 deg N, 103 deg E.', 'Singapore is located at the centre of South-East Asia.', 'Singapore is located in the Northern Hemisphere.', 'Singapore is located to the South of Peninsular Malaysia.'], 'ans': 0, 'explain': 'Latitude and longitude coordinates give the most precise location.'},
    {'q': 'The study of Geography is about the interaction between ____.', 'opts': ['human and physical environments', 'man-made and human environments', 'natural and physical environments', 'human and animal environments'], 'ans': 0, 'explain': 'Geography studies the interaction between human and physical environments.'},
    {'q': 'Which of the following is not a component of the human environment?', 'opts': ['Rubber plantation', 'Power lines', 'River', 'Canal'], 'ans': 2, 'explain': 'A river is a natural (physical) feature, not part of the human environment.'},
    {'q': 'Which one of the following activities will least damage the environment?', 'opts': ['Using water from the river to water the crops', 'Dumping untreated sewage into the sea', 'Building a beach resort', 'Throwing litter into the drains'], 'ans': 0, 'explain': 'Using river water to water crops causes the least environmental damage.'},
    {'q': 'The horizontal lines on a grid map are called ____.', 'opts': ['axis', 'equator', 'northings', 'eastings'], 'ans': 2, 'explain': 'Horizontal grid lines on a map are called northings.'},
    {'q': 'The 0 degree latitude is also known as the ____.', 'opts': ['Tropic of Capricorn', 'Tropic of Cancer', 'Equator', 'North Pole'], 'ans': 2, 'explain': 'The 0 degree line of latitude is the Equator.'},
    {'q': 'Maps i) are tools used in planning; ii) are sources of information; iii) are used to calculate the distances between places accurately; iv) are used to record changes over time. Which is correct?', 'opts': ['i and iii only', 'ii and iv only', 'i, ii and iv only', 'all of the above'], 'ans': 2, 'explain': 'Maps cannot give perfectly accurate distances, so iii is excluded; i, ii and iv are correct.'},
    {'q': 'Which of the following are components of the physical environment?', 'opts': ['Air, land, water, waste', 'Air, soil, buildings, climate', 'Air, land, water, living environment', 'Solar system, temperature, wind, rain'], 'ans': 2, 'explain': 'The physical environment is made up of air, land, water and the living environment.'},
    {'q': 'Which of the following is an example of a human feature?', 'opts': ['Ponds', 'Rivers', 'Reservoirs', 'Sea'], 'ans': 2, 'explain': 'Reservoirs are man-made, so they are a human feature.'},
    {'q': 'Technology is ____.', 'opts': ['old machinery', 'learning new skills', 'teaching new skills to people', 'understanding the environment'], 'ans': 2, 'explain': 'Technology is the application of knowledge and skills to solve problems.'},
    {'q': 'The five main oceans on Earth are Atlantic, Pacific, ____.', 'opts': ['Indian, Arctic and Southern', 'African, Arctic and Southern', 'Indian, African and Southern', 'Indian, Arctic and Antarctica'], 'ans': 0, 'explain': 'The five oceans are Pacific, Atlantic, Indian, Arctic and Southern.'},
    {'q': 'Maps have many uses. Which of the following is not one of them?', 'opts': ['Sources of information', 'Proof of human existence', 'Record of changes', 'Tools used in planning'], 'ans': 1, 'explain': 'Maps are not used as proof of human existence.'},
    {'q': 'All topographical maps have vertical grid lines called ____ and horizontal grid lines called ____.', 'opts': ['Eastings, Northings', 'Northings, Eastings', 'Latitudes, Longitudes', 'Longitudes, Latitudes'], 'ans': 0, 'explain': 'Vertical grid lines are Eastings; horizontal grid lines are Northings.'},
    {'q': 'Different ____ on maps are used to show sizes and levels of details.', 'opts': ['scales', 'rulers', 'grid references', 'arrows'], 'ans': 0, 'explain': 'Different map scales show different sizes and levels of detail.'},
]

SUBTOPIC_RANGES = [('Conventional Symbols', 0, 5), ('Four & Six-Figure Grid References', 5, 10), ('Scale & Measuring Distance', 10, 14), ('Direction & Bearings', 14, 18)]
