QUESTIONS = [
    # --- Subtopic 1: Types of Forces (0-16) ---
    {"q": "A force is best described as a:", "opts": ["Type of energy", "Unit of mass", "Push or a pull", "Form of light"], "ans": 2, "explain": "A force is a push or a pull acting on an object."},
    {"q": "What is the SI unit of force?", "opts": ["Newton", "Joule", "Kilogram", "Watt"], "ans": 0, "explain": "Force is measured in newtons (N)."},
    {"q": "The force that pulls objects towards the centre of the Earth is:", "opts": ["Friction", "Gravitational force", "Magnetic force", "Elastic force"], "ans": 1, "explain": "Gravitational force pulls objects towards the centre of the Earth."},
    {"q": "The force that opposes motion between two surfaces in contact is:", "opts": ["Friction", "Gravity", "Magnetism", "Tension"], "ans": 0, "explain": "Friction is the force that opposes motion between surfaces in contact."},
    {"q": "A magnet attracting an iron nail is an example of:", "opts": ["Magnetic force", "Frictional force", "Gravitational force", "Elastic force"], "ans": 0, "explain": "A magnet exerts a magnetic force on magnetic materials like iron."},
    {"q": "The force in a stretched spring that tries to return it to its original length is a type of:", "opts": ["Magnetic force", "Frictional force", "Electrostatic force", "Elastic force"], "ans": 3, "explain": "A stretched spring exerts an elastic (restoring) force."},
    {"q": "Which is a non-contact force?", "opts": ["Friction", "Push of a hand", "Tension in a rope", "Gravitational force"], "ans": 3, "explain": "Gravitational force acts without objects touching, so it is a non-contact force."},
    {"q": "Which is a contact force?", "opts": ["Magnetic force", "Gravitational force", "Electrostatic force", "Friction"], "ans": 3, "explain": "Friction acts only when surfaces are in contact, so it is a contact force."},
    {"q": "The force exerted by a rope being pulled at both ends is called:", "opts": ["Tension", "Friction", "Gravity", "Upthrust"], "ans": 0, "explain": "Tension is the pulling force transmitted through a rope or string."},
    {"q": "Two like poles of magnets brought together will:", "opts": ["Attract each other", "Have no effect", "Stick together", "Repel each other"], "ans": 3, "explain": "Like magnetic poles repel each other."},
    {"q": "An object floating in water experiences an upward force called:", "opts": ["Tension", "Friction", "Upthrust (buoyant force)", "Magnetic force"], "ans": 2, "explain": "Upthrust is the upward force exerted by a fluid on an object in it."},
    {"q": "Rubbing a plastic ruler on hair so it picks up paper bits shows a:", "opts": ["Magnetic force", "Gravitational force", "Electrostatic force", "Frictional force"], "ans": 2, "explain": "The charged ruler exerts an electrostatic force on the paper."},
    {"q": "Which force keeps the Moon orbiting the Earth?", "opts": ["Friction", "Magnetic force", "Gravitational force", "Elastic force"], "ans": 2, "explain": "Gravitational force between the Earth and Moon keeps the Moon in orbit."},
    {"q": "Air resistance acting on a falling object is a kind of:", "opts": ["Magnetic force", "Frictional force", "Elastic force", "Electrostatic force"], "ans": 1, "explain": "Air resistance is a frictional force opposing motion through air."},
    {"q": "The instrument commonly used to measure force is a:", "opts": ["Thermometer", "Voltmeter", "Spring balance (newton meter)", "Stopwatch"], "ans": 2, "explain": "A spring balance or newton meter is used to measure force in newtons."},
    {"q": "An unlike pole of one magnet near another magnet will:", "opts": ["Repel", "Have no effect", "Melt", "Attract"], "ans": 3, "explain": "Unlike magnetic poles attract each other."},

    # --- Subtopic 2: Effects of Forces (16-32) ---
    {"q": "A force can cause an object at rest to:", "opts": ["Stay still forever", "Lose its mass", "Change colour", "Start moving"], "ans": 3, "explain": "A force can make a stationary object start to move."},
    {"q": "A force acting on a moving object can change its:", "opts": ["Speed or direction", "Mass", "Colour", "Temperature only"], "ans": 0, "explain": "A force can change the speed or direction of a moving object."},
    {"q": "A force can also change an object's:", "opts": ["Mass", "Element", "Shape", "Atomic number"], "ans": 2, "explain": "A force can change the shape of an object, for example squashing or stretching it."},
    {"q": "Which is NOT an effect of a force?", "opts": ["Changing speed", "Creating new matter", "Changing direction", "Changing shape"], "ans": 1, "explain": "Forces can change motion or shape but cannot create new matter."},
    {"q": "When you squeeze a sponge, the force changes its:", "opts": ["Mass", "Colour", "Shape", "Temperature"], "ans": 2, "explain": "Squeezing a sponge changes its shape."},
    {"q": "Kicking a stationary football causes it to move. The force has changed the ball's:", "opts": ["Mass", "State of rest (it now moves)", "Colour", "Material"], "ans": 1, "explain": "The kicking force changes the ball from being at rest to moving."},
    {"q": "A goalkeeper catching a moving ball uses a force to:", "opts": ["Speed it up", "Slow it down and stop it", "Change its colour", "Increase its mass"], "ans": 1, "explain": "The goalkeeper applies a force to slow down and stop the moving ball."},
    {"q": "When two forces act on an object in opposite directions and are equal, the object:", "opts": ["Speeds up", "Always falls", "Has zero resultant force (balanced)", "Changes mass"], "ans": 2, "explain": "Equal and opposite forces are balanced, giving a zero resultant force."},
    {"q": "If a 5 N force acts to the right and a 3 N force acts to the left on a box, the resultant force is:", "opts": ["8 N to the right", "2 N to the right", "2 N to the left", "0 N"], "ans": 1, "explain": "Resultant force = 5 N - 3 N = 2 N to the right."},
    {"q": "If a 6 N force and a 6 N force act in opposite directions on an object, the resultant force is:", "opts": ["12 N", "0 N", "6 N", "3 N"], "ans": 1, "explain": "Equal and opposite forces give a resultant of 0 N (balanced forces)."},
    {"q": "Two forces of 4 N and 7 N act in the same direction on a trolley. The resultant force is:", "opts": ["3 N", "11 N", "28 N", "0 N"], "ans": 1, "explain": "Forces in the same direction add up: 4 N + 7 N = 11 N."},
    {"q": "An object moving at constant speed in a straight line has forces that are:", "opts": ["Balanced", "Unbalanced", "Zero in number", "Always increasing"], "ans": 0, "explain": "Constant speed in a straight line means the forces are balanced."},
    {"q": "When the resultant force on an object is not zero, the object will:", "opts": ["Stay at rest only", "Lose mass", "Change its motion (accelerate, slow down or change direction)", "Change colour"], "ans": 2, "explain": "A non-zero resultant force changes the motion of the object."},
    {"q": "Bending a metal ruler shows that a force can change an object's:", "opts": ["Shape", "Mass", "Colour", "Smell"], "ans": 0, "explain": "Applying a force can bend the ruler, changing its shape."},
    {"q": "Pushing a shopping trolley harder makes it speed up faster. This shows a force can change:", "opts": ["Its colour", "Its material", "Its mass", "Its speed"], "ans": 3, "explain": "A larger force produces a greater change in speed."},
    {"q": "A car going around a bend at constant speed is changing its:", "opts": ["Mass", "Material", "Temperature", "Direction of motion"], "ans": 3, "explain": "A force changes the car's direction as it goes around the bend."},

    # --- Subtopic 3: Friction (32-48) ---
    {"q": "Friction always acts in a direction that:", "opts": ["Helps motion", "Is downward", "Is upward", "Opposes motion"], "ans": 3, "explain": "Friction always acts to oppose the relative motion between surfaces."},
    {"q": "Which surface generally produces the most friction?", "opts": ["Smooth ice", "Rough sandpaper", "Polished glass", "Oiled metal"], "ans": 1, "explain": "Rough surfaces such as sandpaper produce more friction."},
    {"q": "Oil is added between machine parts to:", "opts": ["Increase friction", "Increase mass", "Change colour", "Reduce friction"], "ans": 3, "explain": "Oil acts as a lubricant to reduce friction between moving parts."},
    {"q": "Friction between your shoes and the floor is useful because it:", "opts": ["Helps you walk without slipping", "Makes you slip", "Reduces your mass", "Cools your feet"], "ans": 0, "explain": "Friction provides grip so you can walk without slipping."},
    {"q": "Which is a disadvantage of friction?", "opts": ["It helps cars to grip the road", "It lets us hold objects", "It helps us walk", "It causes wear and produces heat in machines"], "ans": 3, "explain": "Friction causes wear of moving parts and wastes energy as heat."},
    {"q": "Tyre treads on car wheels are designed to:", "opts": ["Reduce friction with the road", "Increase friction with the road for grip", "Look attractive only", "Reduce the car's mass"], "ans": 1, "explain": "Treads increase friction (grip) between the tyre and road, especially when wet."},
    {"q": "Streamlining a car's shape mainly reduces:", "opts": ["Air resistance", "Friction with the road", "Gravity", "Magnetic force"], "ans": 0, "explain": "A streamlined shape reduces air resistance (a type of friction)."},
    {"q": "Which would reduce friction between two surfaces?", "opts": ["Making surfaces rougher", "Using a lubricant such as oil", "Pressing them harder together", "Adding sand between them"], "ans": 1, "explain": "Lubricants such as oil reduce friction between surfaces."},
    {"q": "Friction between moving machine parts often produces unwanted:", "opts": ["Light", "Heat", "Magnetism", "Electricity"], "ans": 1, "explain": "Friction between moving parts produces heat, which can damage machines."},
    {"q": "A parachute works by using a large amount of:", "opts": ["Air resistance to slow the fall", "Magnetic force", "Tension only", "Electrostatic force"], "ans": 0, "explain": "A parachute increases air resistance to slow down the falling parachutist."},
    {"q": "Smooth, polished surfaces have less friction because they:", "opts": ["Have more bumps", "Are heavier", "Are magnetic", "Have fewer bumps to interlock"], "ans": 3, "explain": "Smoother surfaces have fewer bumps to interlock, so friction is lower."},
    {"q": "Ball bearings are used in wheels to:", "opts": ["Increase friction", "Increase mass", "Produce light", "Reduce friction so the wheel turns easily"], "ans": 3, "explain": "Ball bearings reduce friction, allowing wheels to turn smoothly."},
    {"q": "When an object slides over a rough surface, friction causes the object's kinetic energy to change mainly into:", "opts": ["Light energy", "Chemical energy", "Heat energy", "Sound energy only"], "ans": 2, "explain": "Friction converts kinetic energy mainly into heat energy."},
    {"q": "Which situation makes friction useful?", "opts": ["Brakes stopping a bicycle", "Slipping on wet tiles", "Worn-out machine parts", "Overheating engine"], "ans": 0, "explain": "Friction in brakes is useful as it slows down and stops the bicycle."},
    {"q": "Spreading sand on an icy road increases friction so that:", "opts": ["Cars grip the road better", "Cars skid more easily", "Cars become lighter", "The road becomes magnetic"], "ans": 0, "explain": "Sand increases friction, helping car tyres grip the icy road."},
    {"q": "Air resistance on a moving object increases when the object:", "opts": ["Moves slower", "Moves faster", "Stops moving", "Becomes lighter"], "ans": 1, "explain": "Air resistance increases as the speed of the moving object increases."},

    # --- Subtopic 4: Mass, Weight and Gravity (48-64) ---
    {"q": "Mass is a measure of the:", "opts": ["Amount of matter in an object", "Pull of gravity on an object", "Speed of an object", "Volume of an object"], "ans": 0, "explain": "Mass is the amount of matter in an object, measured in kilograms."},
    {"q": "Weight is the:", "opts": ["Amount of matter", "Force of gravity acting on an object", "Speed of an object", "Volume of an object"], "ans": 1, "explain": "Weight is the gravitational force acting on an object's mass."},
    {"q": "The SI unit of mass is the:", "opts": ["Newton", "Joule", "Metre", "Kilogram"], "ans": 3, "explain": "Mass is measured in kilograms (kg)."},
    {"q": "The SI unit of weight is the:", "opts": ["Kilogram", "Joule", "Newton", "Watt"], "ans": 2, "explain": "Weight is a force, so it is measured in newtons (N)."},
    {"q": "On Earth, the gravitational field strength is about:", "opts": ["1 N/kg", "100 N/kg", "10 N/kg", "0.1 N/kg"], "ans": 2, "explain": "Earth's gravitational field strength is about 10 N/kg (9.8 N/kg)."},
    {"q": "The weight of a 2 kg object on Earth (using 10 N/kg) is:", "opts": ["20 N", "2 N", "10 N", "200 N"], "ans": 0, "explain": "Weight = mass x gravitational field strength = 2 kg x 10 N/kg = 20 N."},
    {"q": "Using 10 N/kg, an object of mass 5 kg has a weight of:", "opts": ["50 N", "5 N", "15 N", "0.5 N"], "ans": 0, "explain": "Weight = 5 kg x 10 N/kg = 50 N."},
    {"q": "An object of weight 30 N on Earth (using 10 N/kg) has a mass of:", "opts": ["30 kg", "300 kg", "0.3 kg", "3 kg"], "ans": 3, "explain": "Mass = weight / g = 30 N / 10 N/kg = 3 kg."},
    {"q": "If an astronaut goes to the Moon, their mass will:", "opts": ["Increase", "Decrease", "Stay the same", "Become zero"], "ans": 2, "explain": "Mass is constant; it does not change with location."},
    {"q": "On the Moon, an astronaut's weight is less than on Earth because the Moon has:", "opts": ["More gravity", "No matter", "More air", "Weaker gravity"], "ans": 3, "explain": "The Moon's gravitational field strength is weaker, so weight is less."},
    {"q": "Which statement is correct?", "opts": ["Mass changes with location, weight does not", "Both never change", "Both always change together", "Weight changes with location, mass does not"], "ans": 3, "explain": "Mass stays constant, but weight changes with gravitational field strength."},
    {"q": "Weight is measured using a:", "opts": ["Beam balance", "Spring balance (newton meter)", "Ruler", "Measuring cylinder"], "ans": 1, "explain": "A spring balance measures weight (force) in newtons."},
    {"q": "The Moon's gravitational field strength is about one-sixth of Earth's. A 60 N weight on Earth would be about how much on the Moon?", "opts": ["60 N", "10 N", "360 N", "6 N"], "ans": 1, "explain": "Weight on the Moon is about one-sixth of Earth's: 60 N / 6 = 10 N."},
    {"q": "Two objects of the same mass are on Earth and on the Moon. Compared with the Moon, on Earth the object has:", "opts": ["Less weight", "Less mass", "More weight", "No weight"], "ans": 2, "explain": "Earth's gravity is stronger, so the object weighs more on Earth than on the Moon."},
    {"q": "Which formula correctly relates weight, mass and gravitational field strength?", "opts": ["weight = mass x g", "weight = mass / g", "weight = mass + g", "weight = g / mass"], "ans": 0, "explain": "Weight = mass x gravitational field strength (W = m x g)."},
    {"q": "A 10 kg bag is taken to a planet where g = 4 N/kg. Its weight there is:", "opts": ["40 N", "2.5 N", "14 N", "100 N"], "ans": 0, "explain": "Weight = mass x g = 10 kg x 4 N/kg = 40 N."},

    # --- Subtopic 5: Springs and Hooke's Law (64-80) ---
    {"q": "When a spring is stretched by a small load, its extension is:", "opts": ["Always zero", "Proportional to the load", "Independent of the load", "Negative"], "ans": 1, "explain": "Within the limit, a spring's extension is proportional to the load (Hooke's Law)."},
    {"q": "The 'extension' of a spring means the:", "opts": ["Increase in length when stretched", "Original length", "Mass of the spring", "Weight of the spring"], "ans": 0, "explain": "Extension is the increase in length of a spring when a force is applied."},
    {"q": "Hooke's Law applies only up to the spring's:", "opts": ["Original length", "Colour change", "Limit of proportionality", "Melting point"], "ans": 2, "explain": "Hooke's Law holds only up to the limit of proportionality."},
    {"q": "If a spring stretches 2 cm for every 1 N added, a 3 N load will stretch it by:", "opts": ["2 cm", "3 cm", "6 cm", "9 cm"], "ans": 2, "explain": "Extension = 3 N x 2 cm/N = 6 cm (using proportionality)."},
    {"q": "A spring of natural length 10 cm extends to 14 cm under a load. The extension is:", "opts": ["10 cm", "4 cm", "14 cm", "24 cm"], "ans": 1, "explain": "Extension = stretched length - natural length = 14 cm - 10 cm = 4 cm."},
    {"q": "If too large a load is added beyond the elastic limit, the spring will:", "opts": ["Return to its original shape", "Get shorter", "Become magnetic", "Be permanently stretched out of shape"], "ans": 3, "explain": "Beyond the elastic limit, the spring is permanently deformed."},
    {"q": "A spring that returns to its original length when the load is removed is behaving:", "opts": ["Permanently deformed", "Magnetically", "Elastically", "Chemically"], "ans": 2, "explain": "If a spring returns to its original length, it is behaving elastically."},
    {"q": "On a graph of load against extension within the limit, the line is:", "opts": ["A curve only", "A horizontal line", "A circle", "A straight line through the origin"], "ans": 3, "explain": "Within the limit, load is proportional to extension, giving a straight line through the origin."},
    {"q": "A spring extends 1 cm per 2 N. What load gives an extension of 5 cm?", "opts": ["10 N", "2.5 N", "5 N", "20 N"], "ans": 0, "explain": "Load = 5 cm x (2 N / 1 cm) = 10 N."},
    {"q": "A device that uses a spring's extension to measure force is a:", "opts": ["Thermometer", "Voltmeter", "Spring balance", "Barometer"], "ans": 2, "explain": "A spring balance uses spring extension to measure force."},
    {"q": "Doubling the load on a spring (within its limit) will:", "opts": ["Double the extension", "Halve the extension", "Not change the extension", "Triple the extension"], "ans": 0, "explain": "Extension is proportional to load, so doubling the load doubles the extension."},
    {"q": "A spring has natural length 8 cm. Under a 2 N load it becomes 12 cm long. The extension caused by 2 N is:", "opts": ["12 cm", "4 cm", "8 cm", "20 cm"], "ans": 1, "explain": "Extension = 12 cm - 8 cm = 4 cm."},
    {"q": "Using the spring above (4 cm extension per 2 N), a 4 N load gives an extension of:", "opts": ["2 cm", "4 cm", "16 cm", "8 cm"], "ans": 3, "explain": "Extension is proportional to load: 4 N gives 8 cm extension (twice that of 2 N)."},
    {"q": "If a spring no longer obeys Hooke's Law, the load-extension graph will:", "opts": ["Stay a straight line forever", "Become horizontal at the origin", "Start to curve", "Disappear"], "ans": 2, "explain": "Beyond the limit of proportionality, the graph curves instead of staying straight."},
    {"q": "A heavier load placed on the same spring (within limit) produces a:", "opts": ["Smaller extension", "Zero extension", "Larger extension", "Negative extension"], "ans": 2, "explain": "A larger load produces a larger extension, in proportion to the load."},
    {"q": "Springs are used in mattresses and car suspension mainly because they:", "opts": ["Are magnetic", "Can store elastic potential energy and absorb shocks", "Increase mass", "Produce light"], "ans": 1, "explain": "Springs store elastic potential energy and cushion shocks by compressing and extending."},
]

SUBTOPIC_RANGES = [
    ("Types of Forces", 0, 16),
    ("Effects of Forces", 16, 32),
    ("Friction", 32, 48),
    ("Mass, Weight and Gravity", 48, 64),
    ("Springs and Hooke's Law", 64, 80),
]
